#!/bin/bash
set -e -o pipefail

echo "* Nuking any existing NeoVim configuration"

# Nuke any existing neovim configuration
# neovim config files, here the lazyvim git repo is cloned
rm -rf ~/.config/nvim
# Some lua-related stuff
rm -rf ~/.cache/nvim
# All plugins, gems and lua stuff goes here
rm -rf ~/.local/share/nvim
# lazyvim/nvim logs go here
rm -rf ~/.local/state/nvim

# Install basic tools
echo -e "\n* Installing basic tools"
sudo apt install git

# LazyGit is awesome
echo -e "\n* Installing lazygit"
sudo apt install lazygit

# Install basic lazyvim dependencies
echo -e "\n* Installing basic lazyvim dependencies"
sudo apt install fzf ripgrep fd-find

# Install neovim. Need to install the one from snap:
# apt-based is older and lazyvim requires 0.11+
echo -e "\n* Installing NeoVim"
sudo snap install nvim

# Probably necessary for Lua (used heavily by LazyVim)?
# Fixes Lua-related Query Error: "substitute"
echo -e "\n* Installing luarocks"
sudo apt install luarocks

# Also Fixes Lua-related Query Error: "substitute"
echo -e "\n* Installing nodejs"
sudo apt install nodejs

# Needed to install Ruby-related gems such as "ruby-lsp"
# The reason is that Mason will install the gem into its own folder, which causes the gem and all deps to be installed,
# some of the deps require native extensions.
sudo apt install build-essential

# Nerd Font: downloaded from https://www.nerdfonts.com/
# Used by lazyvim a lot, for all sorts of ascii graphics, keyboard characters etc.
# You want this, otherwise lazyvim will show lots of missing characters.
# NOT NECESSARY FOR KITTY - probably Kitty comes in with NerdFonts bundled in.
if [[ ! -e ~/.fonts/JetBrainsMonoNerdFont*.ttf ]]; then
  #echo -e "\n* Downloading Nerd Font"
  #curl https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip
  #unzip x JetBrainsMono.zip -d ~/.fonts/ -o
  #rm JetBrainsMono.zip
  
  # update font cache
  #fc-cache -fv
  
  # TODO is this necessary? Kitty have NerdFont bundled in?
  #read -p "change the font for your terminal to 'JetBrains Mono Nerd Font'"
else
  echo -e "\n* Nerd Font already installed"
fi

# kitty - recommended for lazyvim
echo -e "\n* Installing Kitty terminal"
sudo apt install kitty

# Install Ruby - not strictly necessary for LazyGit, but
# I want to set up Ruby LazyVim dev env.
echo -e "\n* Installing Ruby"
sudo snap install ruby --classic


# Configure LazyVim according to https://www.lazyvim.org/installation
echo -e "\n* Configuring NeoVim for LazyVim"
git clone https://github.com/LazyVim/starter ~/.config/nvim

# Done!
echo -e "\n* Done. Run nvim from kitty; then run :LazyHealth"
echo "- Install LazyVim/Ruby: https://www.lazyvim.org/extras/lang/ruby"

